FROM node:trixie-slim


LABEL software="jbrowse" \ 
    maintainer="Sebastian Bassi <sebastian@toyoko.io>" \
    about.summary="CLI for jbrowse (CLI only, not the web server)" \ 
    about.home="https://jbrowse.org/jb2/" \ 
    software.version="3.6.4" \ 
    about.license="Apache 2.0"


RUN npm install -g @jbrowse/cli@3.6.4



